### ISSUE TITLE
Shorter notation

### ISSUE THREAD

**Issue by MarcelBreuers** [James-Yu/external-file-card#2]
Is it possible to implement a shorter notation?

Use [](obsidian://ef#HeliophysicsI_Schrijver.pdf)
to display HeliophysicsI_Schrijver.pdf

instead of the conventional redundant notation
[HeliophysicsI_Schrijver.pdf](obsidian://ef#HeliophysicsI_Schrijver.pdf)

By the way, this is a great plugin!

**Comment by James-Yu** [comment]
Thanks for filing the issue. However, I cannot see the difference. Did you miss some content? Same applies to #3.

**Comment by MarcelBreuers** [comment]
Sorry for the mistakes in my first comment

I would like to use shorter smart notation
[](obsidian://ef#HeliophysicsI_Schrijver.pdf)

Instead of conventional obsidian markdown
[HeliophysicsI_Schrijver.pdf](obsidian://ef#HeliophysicsI_Schrijver.pdf)

Curently
[](obsidian://ef#HeliophysicsI_Schrijver.pdf) will only show []

But I would like a smart interpretation where

[](obsidian://ef#HeliophysicsI_Schrijver.pdf) will show HeliophysicsI_Schrijver.pdf 

Thanks in advance! Your plugin is very helpful for me.

**Comment by James-Yu** [comment]
This violates Markdown syntax, and the plugin cannot provide such feature due to limit of obsidian.
