### ISSUE TITLE
Partial path

### ISSUE THREAD

**Issue by MarcelBreuers** [James-Yu/external-file-card#3]
In would like to use a partial path notation.

[HeliophysicsI_Schrijver.pdf](obsidian://ef#\Astronomy\HeliophysicsI_Schrijver.pdf )

instead of:

[HeliophysicsI_Schrijver.pdf](obsidian://efHeliophysicsI_Schrijver.pdf )

Is would like to use the partial path notation to have a hint in which folder the external document can be found, even when i just read the raw markdown note without plugin.

**Comment by MarcelBreuers** [comment]
Sorry I mean. In would like to use a partial path notation. Then all the examples would be valid.

In would like to use a partial path notation.

obsidian://ef#HeliophysicsI_Schrijver.pdf

obsidian://ef#/Astronomy/HeliophysicsI_Schrijver.pdf

obsidian://ef#/Ebook/Astronomy/HeliophysicsI_Schrijver.pdf

For this file:
E:\doc\coredoc\book\Ebook\Astronomy\HeliophysicsI_Schrijver.pdf

I would like to use the partial path notation to have a hint in which folder the external document can be found, even when i just read the raw markdown note without plugin. My own python application for editing notes can dos this.

**Comment by James-Yu** [comment]
The current implementation already supports partial path. Just make sure the partial path is indeed under your defined external paths.

One more thing, URI cannot contain `/` symbol. So you can select the paths and use `Insert File Link` command to convert the path. This is a limit by URI, this plugin cannot avoid it.

**Comment by MarcelBreuers** [comment]
Thanks!

'%2' works
[works /Astronomy/HeliophysicsI_Schrijver.pdf](obsidian://ef#%2FAstronomy%2FHeliophysicsI_Schrijver.pdf)

I thought a forward slash '/' is a valid URI character. It would be an advantage for readability if it could be used in your plugin.
